# Generated by Django 5.0.6 on 2024-07-11 07:10

import django.db.models.deletion
import drf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=drf.models.image_upload_handler)),
                ('blog', models.ForeignKey(default=drf.models.Blog, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='drf.blog')),
            ],
        ),
    ]
