# Generated by Django 5.0.6 on 2024-07-10 07:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.image_upload_handler),
        ),
        migrations.AddField(
            model_name='employee',
            name='joinig_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
