# Generated by Django 5.0.6 on 2024-07-01 05:35

import recipe.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[recipe.validators.validate_unit_of_measurements]),
        ),
    ]
