# Generated by Django 5.0.6 on 2024-07-04 10:29

import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipeingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='image',
            field=models.ImageField(upload_to=recipe.models.recipe_ingredient_image_upload_handler),
        ),
    ]
