# Generated by Django 5.0.6 on 2024-06-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
