# Generated by Django 5.0.6 on 2024-07-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
